### ISSUE TITLE
zlib version issue

### ISSUE THREAD

**Issue by bdureau** [KooleControls/ESPTool#1]
Hello 
I was trying to compile your test app and I am getting the following error. could you help?
Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'zlib.net 1.0.4' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	ESPTool	E:\data\Csharp\ESPTool-main\ESPTool\ESPTool.csproj	1

**Comment by vanBassum** [comment]
I missed this issue completely, I see you have fixed this already. Ill see if I can merge this to this repo, thanks for fixing.
