### ISSUE TITLE
Licence file is missing in this project

### ISSUE THREAD

**Issue by mgeramb** [KooleControls/ESPTool#8]
I want to use this library in a GNU General Public License v3.0 library. Would this be allowed?

**Comment by vanBassum** [comment]
Sure go ahead.

Please add some link to this repo. In case people want to submit pull requests 

Oh and let me know what your working on, im curious ;)

**Comment by thewhobox** [comment]
We want to add an automatic flash function in our Toolbox: https://github.com/OpenKNX/OpenKNX.Toolbox

**Comment by vanBassum** [comment]
Thanks for letting me know, I have added the license file to the repo.
