### ISSUE TITLE
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll

### ISSUE THREAD

**Issue by zejulio** [KooleControls/ESPTool#9]
Hello,

I'm trying again to get back to this, I've already managed to make this example work, but now when I do open and enter bootloader, it say's OK, when I go to Sync it say's FAIL...
I've checked the logs on C# and it's getting "Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in mscorlib.dll"
Any ideia what can this be?

Thanks!

**Comment by vanBassum** [comment]
Firstly, bootloader OK, doesn't verify if the device is actually in the bootloader. It just means that the comport executed the sequence of the DTR and RTS pins that should put your device into bootloader. But your hardware needs to support this.
https://github.com/KooleControls/ESPTool/blob/c9a6dd71e224ed9c707084d5cc039440dd9731b2/ESPTool/Com/Communicator.cs#L72

When you run the sync, this is where the app tries to communicate with the bootloader of the device. As you can see, this is the code that runs when you try to sync a device:
https://github.com/KooleControls/ESPTool/blob/c9a6dd71e224ed9c707084d5cc039440dd9731b2/ESPTool/Devices/Device.cs#L51

Here a cancellation token is make that will cancel after 100ms.
In the meantime, the code tries to send the SYNC frame to your device.
https://github.com/KooleControls/ESPTool/blob/c9a6dd71e224ed9c707084d5cc039440dd9731b2/ESPTool/Loaders/Loader.cs#L95

Either the device responds within 100ms or the timeout of 100ms will hit first, and you get your exception.

So, either:
- Your device is not running in the bootloader, (Check if your hardware supports this)
- Your device doesn't respond to the sync command. (Maybe your device has a different bootloader)
- Your device doesn't respond within the 100ms timeout, you can try to increase this timeout to see what happens.

**Comment by vanBassum** [comment]
@zejulio I will close this issue now, if you still need support, please reopen the issue.
